services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: shamil2
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: