env: "local" #local, dev ,prod
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
database:
  user: "postgres"
  password: "mysecretpassword"
  host: "localhost"
  port: "5436"
  dbname: "shamil"